name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Debug Directory Contents
      run: Get-ChildItem -Path "C:\Users\Administrator\actions-runner\_work\deploi-githubactions-test\deploi-githubactions-test\d3ba3fe7-1034-4238-aaa2-a69df5942b67\YAHYA280-deploi-githubactions-test-6a7d4ed180b9e6a1c9c951b536d2acd15fa91641"
      shell: pwsh

    - name: Conditional Cleanup
      run: |
        if (Test-Path -Path "C:\Users\Administrator\actions-runner\_work\deploi-githubactions-test\deploi-githubactions-test\d3ba3fe7-1034-4238-aaa2-a69df5942b67\YAHYA280-deploi-githubactions-test-6a7d4ed180b9e6a1c9c951b536d2acd15fa91641\.github") {
          Remove-Item -Path "C:\Users\Administrator\actions-runner\_work\deploi-githubactions-test\deploi-githubactions-test\d3ba3fe7-1034-4238-aaa2-a69df5942b67\YAHYA280-deploi-githubactions-test-6a7d4ed180b9e6a1c9c951b536d2acd15fa91641\.github" -Force -Recurse
        }
      shell: pwsh
